language: php
php: 5.4

before_install:
  - wget http://framework.zend.com/releases/ZendFramework-1.11.11/ZendFramework-1.11.11-minimal.tar.gz -O - | tar -xz
  - export ZF_HOME=$PWD/ZendFramework-1.11.11-minimal

install:
  - export PATH=$ZF_HOME/bin:$PATH

before_script:
  - phpunit --version
  - ant -version
  - zf.sh show version
  - zf.sh create project .
  - zf.sh enable layout
  - ln -s $ZF_HOME/library/Zend library/Zend

script:
  - ant -buildfile public/build/build.xml
  - phpunit

notifications:
  email: false
